version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    target_branch: "master"
    default_assignees:
      - "Sid200026"
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
    target_branch: "master"
    default_assignees:
      - "Sid200026"
