import {
  enable,
  profile,
  description,
  descriptionColor,
  skills,
  background,
  menuColor,
  menuBackground,
  resumeURL,
  resumeButtonText,
  resumeButtonBorder,
  resumeButtonColor,
  resumeButtonHoverBG,
  resumeButtonHoverColor,
  resumeButtonBG,
  resumeHoverEnable,
  skillsBackground,
  pageHeadline,
  pageHeadlineColor,
  mediaHandles,
} from '../constants/about_me_page';

const aboutMe = {
  [enable]: false,
  [pageHeadline]: '',
  [pageHeadlineColor]: '#ffffff',
  [profile]: {},
  [description]: '',
  [descriptionColor]: '#000000',
  [skills]: [],
  [skillsBackground]: '#ffffff',
  [background]: '#ffffff',
  [menuBackground]: '#000000',
  [menuColor]: '#ffffff',
  [resumeURL]: '',
  [resumeButtonText]: 'Resume',
  [resumeButtonBorder]: '#000000',
  [resumeButtonColor]: '#ffffff',
  [resumeButtonHoverBG]: '#ffffff',
  [resumeButtonHoverColor]: '#000000',
  [resumeButtonBG]: '#ffffff',
  [resumeHoverEnable]: false,
  [mediaHandles]: [],
};

export { aboutMe };
