import {
  greetingText,
  greetingColor,
  nameText,
  nameColor,
  nameBold,
  specialisationText,
  specialisationColor,
  particleTheme,
  buttonText,
  buttonBorder,
  buttonColor,
  buttonHoverBG,
  buttonHoverColor,
  font,
  metadesc,
  title,
  enable,
} from '../constants/introduction_page';

const introduction = {
  [enable]: false,
  [greetingText]: '',
  [greetingColor]: '#ffffff',
  [nameText]: '',
  [nameColor]: 'blue',
  [nameBold]: true,
  [specialisationText]: [],
  [specialisationColor]: 'white',
  [particleTheme]: '',
  [buttonText]: 'Visit My Profile',
  [buttonBorder]: 'black',
  [buttonColor]: 'white',
  [buttonHoverBG]: 'blue',
  [buttonHoverColor]: 'black',
  [font]: 'Times New Roman, Times, serif, Arial, Helvetica',
  [metadesc]: 'An open source personal website generator',
  [title]: 'WebGen',
};

export { introduction };
