import {
  greetingText,
  greetingColor,
  nameText,
  nameColor,
  nameBold,
  specialisationText,
  specialisationColor,
  particleTheme,
  buttonText,
  buttonBorder,
  buttonColor,
  buttonHoverBG,
  buttonHoverColor,
  font,
  metadesc,
  title,
  enable,
  hoverEffect,
  favicon,
} from '../constants/introduction_page';

const introduction = {
  [enable]: false,
  [greetingText]: '',
  [greetingColor]: '#ffffff',
  [nameText]: '',
  [nameColor]: '#0000ff',
  [nameBold]: true,
  [specialisationText]: [],
  [specialisationColor]: '#ffffff',
  [particleTheme]: '',
  [buttonText]: 'Visit My Profile',
  [buttonBorder]: '#000000',
  [buttonColor]: '#ffffff',
  [buttonHoverBG]: '#0000ff',
  [buttonHoverColor]: '#ffffff',
  [font]: 'Times New Roman, Times, serif, Arial, Helvetica',
  [metadesc]: '',
  [title]: '',
  [hoverEffect]: false,
  [favicon]: '',
};

export { introduction };
