const introductionInitial = ({
  enable,
  greetingText,
  greetingColor,
  nameText,
  nameColor,
  nameBold,
  specialisationText,
  specialisationColor,
  particleTheme,
  particleThemeBackgroundColor,
  particleThemeEntityColor,
  buttonText,
  buttonBorder,
  buttonColor,
  buttonHoverBG,
  buttonHoverColor,
  font,
  metadesc,
  title,
  hoverEffect,
  favicon,
}) => `\
import {
  greetingText,
  greetingColor,
  nameText,
  nameColor,
  nameBold,
  specialisationText,
  specialisationColor,
  particleTheme,
  particleThemeBackgroundColor,
  particleThemeEntityColor,
  buttonText,
  buttonBorder,
  buttonColor,
  buttonHoverBG,
  buttonHoverColor,
  font,
  metadesc,
  title,
  enable,
  hoverEffect,
  favicon,
} from '../constants/introduction_page';

const introduction = {
  [enable]: ${enable},
  [greetingText]: \`${greetingText}\`,
  [greetingColor]: \`${greetingColor}\`,
  [nameText]: \`${nameText}\`,
  [nameColor]: \`${nameColor}\`,
  [nameBold]: ${nameBold},
  [specialisationText]: ${JSON.stringify(specialisationText)},
  [specialisationColor]: \`${specialisationColor}\`,
  [particleTheme]: \`${particleTheme}\`,
  [particleThemeBackgroundColor]: \`${particleThemeBackgroundColor}\`,
  [particleThemeEntityColor]: \`${particleThemeEntityColor}\`,
  [buttonText]: \`${buttonText}\`,
  [buttonBorder]: \`${buttonBorder}\`,
  [buttonColor]: \`${buttonColor}\`,
  [buttonHoverBG]: \`${buttonHoverBG}\`,
  [buttonHoverColor]: \`${buttonHoverColor}\`,
  [font]: \`${font}\`,
  [metadesc]: \`${metadesc}\`,
  [title]: \`${title}\`,
  [hoverEffect]: ${hoverEffect},
  [favicon]: ${JSON.stringify(favicon)},
};

export { introduction };
`;

module.exports = { introductionInitial };
